# Generated by Django 4.0.6 on 2022-08-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='private',
            new_name='public',
        ),
    ]
